(function(){
const K='TT_CC_ADVANCES';
let A=[];try{A=JSON.parse(localStorage.getItem(K)||'[]')}catch(e){}if(!Array.isArray(A))A=[];
const M=x=>String(x||'').slice(0,7),F=n=>Number(n||0).toLocaleString('vi-VN')+' đ',E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const aw=(id)=>data.workshops.findIndex(w=>w.id===id), ads=(wid,m)=>A.filter(a=>a.w===wid&&M(a.d)===m), at=(wid,m)=>ads(wid,m).reduce((s,a)=>s+ +a.v,0);
function tab(){let t=document.getElementById('tabs');if(!t||t.querySelector('#advTab'))return;let b=document.createElement('button');b.id='advTab';b.className='tab';b.textContent='💸 TẠM ỨNG';b.onclick=()=>{view='advance';render()};t.appendChild(b)}
function save(){localStorage.setItem(K,JSON.stringify(A))}
function advance(){let c=document.getElementById('content'),w=data.workshops[active]||data.workshops[0],list=ads(w.id,month),total=list.reduce((s,a)=>s+ +a.v,0);c.innerHTML=`<div class="card"><div class="bar"><div><div class="title">💸 TẠM ỨNG LƯƠNG</div><div class="hint">Theo từng xưởng và từng tháng</div></div><div class="controls"><label>🏭 Xưởng</label><select id="aw">${data.workshops.map((x,i)=>`<option value="${E(x.id)}" ${i===active?'selected':''}>${E(x.name)}</option>`).join('')}</select><label>Tháng</label><input id="am" type="month" value="${month}"></div></div><div class="row"><input id="an" placeholder="Tên người nhận"><input id="ad" type="date" value="${month}-01"><input id="av" type="number" min="0" placeholder="Số tiền tạm ứng"><input id="ax" placeholder="Ghi chú"></div><div class="row"><button class="green" onclick="TTadd()">＋ Lưu tạm ứng</button></div><div class="stats"><div class="stat">Tổng tạm ứng: <b class="money">${F(total)}</b></div></div><div class="tableWrap"><table><thead><tr><th>Ngày</th><th>Người</th><th>Số tiền</th><th>Ghi chú</th><th></th></tr></thead><tbody>${list.length?list.map(a=>`<tr><td>${E(a.d)}</td><td class="left">${E(a.n)}</td><td class="money">${F(a.v)}</td><td class="left">${E(a.x)}</td><td><button class="danger" onclick="TTdel('${a.id}')">Xóa</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Chưa có tạm ứng.</td></tr>'}</tbody></table></div></div>`;document.getElementById('aw').onchange=e=>{active=aw(e.target.value);render()};document.getElementById('am').onchange=e=>{month=e.target.value;render()}}
window.TTadd=()=>{let w=document.getElementById('aw').value,n=document.getElementById('an').value.trim(),d=document.getElementById('ad').value,v=+document.getElementById('av').value||0,x=document.getElementById('ax').value.trim();if(!n)return toast('Nhập tên người nhận');if(!d||v<=0)return toast('Nhập ngày và số tiền');A.push({id:'a'+Date.now(),w,n,d,v,x});save();month=M(d);active=aw(w);render();toast('Đã lưu tạm ứng')};window.TTdel=id=>{if(confirm('Xóa khoản tạm ứng này?')){A=A.filter(a=>a.id!==id);save();render()}};
function summary(){let c=document.getElementById('content'),rows=data.workshops.map(w=>{let rs=Object.keys(data.records||{}).filter(k=>k.startsWith(w.id+'|')&&M(k.slice(-10))===month).map(k=>data.records[k]);let sal=rs.reduce((s,r)=>s+ +(r.wage||0)+(typeof otMoney==='function'?otMoney(r):0),0),adv=at(w.id,month);return{w,sal,adv,net:sal-adv,days:rs.length,people:new Set(rs.map(r=>r.name)).size}}),g=rows.reduce((s,x)=>s+x.sal,0),a=rows.reduce((s,x)=>s+x.adv,0);c.innerHTML=`<div class="card summaryBox"><div class="bar"><div><div class="title">💰 TỔNG LƯƠNG</div><div class="hint">Đã tự động trừ tạm ứng</div></div><div class="controls"><label>Tháng</label><input id="sm" type="month" value="${month}"></div></div><div class="stats"><div class="stat">Tổng lương: <b>${F(g)}</b></div><div class="stat">Tạm ứng: <b>${F(a)}</b></div><div class="stat summaryTotal">CÒN PHẢI TRẢ: ${F(g-a)}</div></div><div class="tableWrap"><table><thead><tr><th>Xưởng</th><th>Số người</th><th>Ngày công</th><th>Tổng lương</th><th>Tạm ứng</th><th>Còn phải trả</th></tr></thead><tbody>${rows.map(x=>`<tr><td class="left"><b>${E(x.w.name)}</b></td><td>${x.people}</td><td>${x.days}</td><td>${F(x.sal)}</td><td>${F(x.adv)}</td><td class="summaryTotal">${F(x.net)}</td></tr>`).join('')}<tr><th>TỔNG</th><th>${rows.reduce((s,x)=>s+x.people,0)}</th><th>${rows.reduce((s,x)=>s+x.days,0)}</th><th>${F(g)}</th><th>${F(a)}</th><th>${F(g-a)}</th></tr></tbody></table></div></div>`;document.getElementById('sm').onchange=e=>{month=e.target.value;render()}}
const R=window.render;window.render=function(){R();tab();if(view==='advance')advance();if(view==='summary')summary()};setTimeout(tab,0)
})();